---
title: "About"
bibliography: veracruz.bib
---

This website is for participants in the nonparametric workshop being held May 20-21, 2024, in Veracruz, Mexico. Material will be based on @racine_2019. The workshop will be run by Professor Jeffrey S. Racine who currently works at McMaster University in Hamilton, Ontario, Canada.

You can contact him at <a href="mailto:racinej@mcmaster.ca">racinej\@mcmaster.ca</a> and his professional website can be found at <a href="https://facsocsci.mcmaster.ca/people/racinej">facsocsci.mcmaster.ca/people/racinej</a>

## Biography

Jeffrey S. Racine (Ph.D. University of Western Ontario, 1989, Aman Ullah, Supervisor) is a Professor in the Department of Economics and a Professor in the Graduate Program in Statistics in the Department of Mathematics and Statistics at McMaster University. He occupies the Senator William McMaster Chair in Econometrics and is a Fellow of the Journal of Econometrics. He has held previous appointments at Syracuse University, the University of South Florida, the University of California San Diego (two-year visiting appointment), and York University.

His research interests include nonparametric estimation and inference, shape constrained estimation, cross-validatory model selection, frequentist model averaging, nonparametric instrumental methods, and entropy-based measures of dependence and their statistical underpinnings. He is also interested in parallel distributed computing paradigms and their application to computationally intensive nonparametric estimators.

He is currently serving as an Associate Editor for the journal Econometric Reviews.

He has co-authored the textbook Nonparametric Econometrics: Theory and Practice (joint with Qi Li, published by Princeton University Press, 2007, with a Chinese translation published in 2015), the monograph Nonparametric Econometrics: A Primer (published by Foundations and Trends in Econometrics, 2008, with a Russian translation published in the journal Quantile in 2008), the textbook Reproducible Econometrics Using R (published by Oxford University Press, 2018), and the textbook An Introduction to the Advanced Theory and Practice of Nonparametric Econometrics: A Replicable Approach Using R (published by Cambridge University Press, 2019). He has published extensively in peer reviewed journals in his field and has co-authored the R packages `np` and `crs` that are available on the Comprehensive R Archive Network (CRAN).
